### ISSUE TITLE
juxtapose/slider creating unintended effect

### ISSUE THREAD

**Issue by shenzlik** [umich-hist-399/campus-histories#5]
the image on the right has white space on the left when the slider is focused on it. Is there a way to avoid this? (in acquisition of public schools essay).

**Comment by fredgibbs** [comment]
This seems to be caused by the new color image not being wide enough to cover the entire juxtapose viewer. To be safe, I think images should be at least 700 pixels wide to cover the space. It would be best to make sure we have large enough images, but if this is too difficult or annoying at this point, I can try to force them to be that size--but images can look grainy when blown up beyond their normal size.

**Comment by shenzlik** [comment]
I see. I can see about making the color image wider. If need be, I can always re-take the photo.
